# Load Banknote Data

In [2]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Dense
from tensorflow.python.keras.wrappers.scikit_learn import KerasRegressor
import tensorflow as tf

In [3]:
from urllib.request import urlopen
url = 'http://archive.ics.uci.edu/ml/machine-learning-databases/00267/data_banknote_authentication.txt'
raw_data = urlopen(url)
dataset = np.loadtxt(raw_data, delimiter=",")
print(dataset.shape)

(1372, 5)


In [4]:
df = pd.DataFrame(dataset, columns = ['variance of Wavelet Transformed image','skewness of Wavelet Transformed image','curtosis of Wavelet Transformed image','entropy of image','class'])

In [5]:
df.head()

variance of Wavelet Transformed image  ...  class
0                                3.62160  ...    0.0
1                                4.54590  ...    0.0
2                                3.86600  ...    0.0
3                                3.45660  ...    0.0
4                                0.32924  ...    0.0

[5 rows x 5 columns]

In [6]:
x = df.iloc[:,0:4].values
y = df.iloc[:,-1].values

In [20]:
x

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [21]:
y

array([0., 0., 0., ..., 1., 1., 1.])

In [7]:
y=np.reshape(y, (-1,1))

# Normalize Data

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.2, random_state=0)

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [63]:
a=1
b=0

In [10]:
def my_func(x):
  return(a*x+b)

In [17]:

ann = tf.keras.models.Sequential()
 

# Fit ANN

In [18]:
#First hidden layer
ann.add(tf.keras.layers.Dense(units=7, activation='relu'))

In [19]:
#Second hidden layer
ann.add(tf.keras.layers.Dense(units=7, activation='relu'))

In [20]:
#Output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [21]:
ann.compile(optimizer='sgd',loss='binary_crossentropy', metrics=['accuracy'])

In [22]:
ann.fit(x_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
35/35 [==============================] - 1s 1ms/step - loss: 0.6626 - accuracy: 0.6427
Epoch 2/100
35/35 [==============================] - 0s 1ms/step - loss: 0.6245 - accuracy: 0.7384
Epoch 3/100
35/35 [==============================] - 0s 1ms/step - loss: 0.5886 - accuracy: 0.7201
Epoch 4/100
35/35 [==============================] - 0s 2ms/step - loss: 0.5528 - accuracy: 0.7420
Epoch 5/100
35/35 [==============================] - 0s 1ms/step - loss: 0.5172 - accuracy: 0.8013
Epoch 6/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4827 - accuracy: 0.8459
Epoch 7/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4497 - accuracy: 0.8979
Epoch 8/100
35/35 [==============================] - 0s 1ms/step - loss: 0.4187 - accuracy: 0.9234
Epoch 9/100
35/35 [==============================] - 0s 1ms/step - loss: 0.3902 - accuracy: 0.9407
Epoch 10/100
35/35 [==============================] - 0s 2ms/step - loss: 0.3637 - accuracy: 0.9480
Epoch 11/

#Calculating Accuracy

In [23]:
from sklearn.metrics import accuracy_score

In [24]:
# predict test set
yhat = ann.predict_classes(x_test)
# evaluate predictions
score = accuracy_score(y_test, yhat)
print('Accuracy: %.3f' % score)

Accuracy: 1.000


/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


# Prediction

In [25]:
print(ann.predict(sc.transform([[3.6,8.6,-0.3,-0.8]])))

[[2.3289417e-06]]


In [26]:
print(ann.predict(sc.transform(x_test)))

[[0.97949135]
 [0.5253929 ]
 [0.98703325]
 [0.7920063 ]
 [0.5275302 ]
 [0.3901772 ]
 [0.836439  ]
 [0.74990165]
 [0.9858305 ]
 [0.98814756]
 [0.85017896]
 [0.2880323 ]
 [0.9863256 ]
 [0.2789911 ]
 [0.5151809 ]
 [0.63280034]
 [0.9899161 ]
 [0.98461455]
 [0.6621151 ]
 [0.5899242 ]
 [0.98278725]
 [0.71864486]
 [0.32768887]
 [0.98703647]
 [0.9857999 ]
 [0.9847996 ]
 [0.556738  ]
 [0.9875798 ]
 [0.65889955]
 [0.9244006 ]
 [0.98672986]
 [0.92228425]
 [0.98565686]
 [0.9869045 ]
 [0.98861504]
 [0.7980915 ]
 [0.6958896 ]
 [0.9895767 ]
 [0.94487655]
 [0.98007226]
 [0.9638568 ]
 [0.99030864]
 [0.7102028 ]
 [0.9623966 ]
 [0.98713356]
 [0.98227584]
 [0.44349357]
 [0.66395533]
 [0.986853  ]
 [0.828592  ]
 [0.71237355]
 [0.9943979 ]
 [0.94468457]
 [0.9885372 ]
 [0.9863438 ]
 [0.56800985]
 [0.98660886]
 [0.9849862 ]
 [0.9203033 ]
 [0.9889133 ]
 [0.98493373]
 [0.87627363]
 [0.46398017]
 [0.3288741 ]
 [0.73128676]
 [0.98951757]
 [0.98143506]
 [0.98354757]
 [0.9806675 ]
 [0.6988707 ]
 [0.9830485 ]
 [0.38

In [27]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 

In [29]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)


[[157   0]
 [  0 118]]


1.0

In [30]:
classification_report(y_test,y_pred)

'              precision    recall  f1-score   support\n\n         0.0       1.00      1.00      1.00       157\n         1.0       1.00      1.00      1.00       118\n\n    accuracy                           1.00       275\n   macro avg       1.00      1.00      1.00       275\nweighted avg       1.00      1.00      1.00       275\n'